# Generated by Django 5.0.3 on 2024-03-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome do Pokemon')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo do Pokemon')),
            ],
        ),
    ]
