# Generated by Django 5.0.3 on 2024-03-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='passiva',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Passiva do Pokemon'),
        ),
    ]
