# Generated by Django 5.0.3 on 2024-03-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemon_passiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='movimentos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Movimentos do Pokemon'),
        ),
    ]
