# Generated by Django 5.0.3 on 2024-03-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViaCepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.IntegerField(verbose_name='Cep do usuário')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro do usuario')),
                ('complemento', models.CharField(max_length=100, verbose_name='Complemento do usuario')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro do usuario')),
                ('localidade', models.CharField(max_length=100, verbose_name='Localidade do usuario')),
                ('uf', models.CharField(max_length=100, verbose_name='Estado do usuario')),
            ],
        ),
    ]
