# Generated by Django 5.0.3 on 2024-03-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segundoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viacepmodel',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro do usuario'),
        ),
        migrations.AlterField(
            model_name='viacepmodel',
            name='cep',
            field=models.IntegerField(max_length=20, verbose_name='Cep do usuário'),
        ),
        migrations.AlterField(
            model_name='viacepmodel',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento do usuario'),
        ),
        migrations.AlterField(
            model_name='viacepmodel',
            name='localidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidade do usuario'),
        ),
        migrations.AlterField(
            model_name='viacepmodel',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro do usuario'),
        ),
        migrations.AlterField(
            model_name='viacepmodel',
            name='uf',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado do usuario'),
        ),
    ]
