# Generated by Django 5.0.3 on 2024-03-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segundoapp', '0002_alter_viacepmodel_bairro_alter_viacepmodel_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viacepmodel',
            name='cep',
            field=models.CharField(max_length=20, verbose_name='Cep do usuário'),
        ),
    ]
